INSERT INTO city(id,province_id,name,en_name) VALUES ('1', '1', ' آذرشهر', 'Azarshahr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('2', '1', ' اسکو', 'Osku');
INSERT INTO city(id,province_id,name,en_name) VALUES ('3', '1', ' اهر', 'Ahar');
INSERT INTO city(id,province_id,name,en_name) VALUES ('4', '1', ' بستان آباد', 'Bostanabad');
INSERT INTO city(id,province_id,name,en_name) VALUES ('5', '1', ' بناب', 'Bonab');
INSERT INTO city(id,province_id,name,en_name) VALUES ('6', '1', ' تبریز', 'Tabriz');
INSERT INTO city(id,province_id,name,en_name) VALUES ('7', '1', ' جلفا', 'Jolfa');
INSERT INTO city(id,province_id,name,en_name) VALUES ('8', '1', ' چار اویماق', 'Charuymaq');
INSERT INTO city(id,province_id,name,en_name) VALUES ('9', '1', ' سراب', 'Sarab');
INSERT INTO city(id,province_id,name,en_name) VALUES ('10', '1', ' شبستر', 'Shabestar');
INSERT INTO city(id,province_id,name,en_name) VALUES ('11', '1', ' عجبشیر', 'Ajab Shir');
INSERT INTO city(id,province_id,name,en_name) VALUES ('12', '1', ' کلیبر', 'Kaleybar');
INSERT INTO city(id,province_id,name,en_name) VALUES ('13', '1', ' مراغه', 'Maragheh');
INSERT INTO city(id,province_id,name,en_name) VALUES ('14', '1', ' مرند', 'Marand');
INSERT INTO city(id,province_id,name,en_name) VALUES ('15', '1', ' ملکان', 'Malekan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('16', '1', ' میانه', 'Mianeh');
INSERT INTO city(id,province_id,name,en_name) VALUES ('17', '1', ' ورزقان', 'Varzaqan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('18', '1', ' هریس', 'Heris');
INSERT INTO city(id,province_id,name,en_name) VALUES ('19', '1', 'هشترود', 'Hashtrud');
INSERT INTO city(id,province_id,name,en_name) VALUES ('20', '2', ' ارومیه', 'Urmia');
INSERT INTO city(id,province_id,name,en_name) VALUES ('21', '2', ' اشنویه', 'Oshnavieh');
INSERT INTO city(id,province_id,name,en_name) VALUES ('22', '2', ' بوکان', 'Bukan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('23', '2', ' پیرانشهر', 'Piranshahr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('24', '2', ' تکاب', 'Takab');
INSERT INTO city(id,province_id,name,en_name) VALUES ('25', '2', ' چالدران', 'Chaldoran');
INSERT INTO city(id,province_id,name,en_name) VALUES ('26', '2', ' خوی', 'Khoy');
INSERT INTO city(id,province_id,name,en_name) VALUES ('27', '2', ' سردشت', 'Sardasht');
INSERT INTO city(id,province_id,name,en_name) VALUES ('28', '2', ' سلماس', 'Salmas');
INSERT INTO city(id,province_id,name,en_name) VALUES ('29', '2', ' شاهین دژ', 'Shahin Dezh\r\n');
INSERT INTO city(id,province_id,name,en_name) VALUES ('30', '2', ' ماکو', 'Maku');
INSERT INTO city(id,province_id,name,en_name) VALUES ('31', '2', ' مهاباد', 'Mahabad');
INSERT INTO city(id,province_id,name,en_name) VALUES ('32', '2', ' میاندوآب', 'Miandoab');
INSERT INTO city(id,province_id,name,en_name) VALUES ('33', '2', ' نقده', 'Naqadeh');
INSERT INTO city(id,province_id,name,en_name) VALUES ('34', '3', ' اردبیل', 'Ardabil');
INSERT INTO city(id,province_id,name,en_name) VALUES ('35', '3', ' بیله سوار', 'Bileh Bileh Savar');
INSERT INTO city(id,province_id,name,en_name) VALUES ('36', '3', ' پارس آباد', 'Parsabad');
INSERT INTO city(id,province_id,name,en_name) VALUES ('37', '3', ' خلخال', 'Khalkhal');
INSERT INTO city(id,province_id,name,en_name) VALUES ('38', '3', ' کوثر', 'Kowsar');
INSERT INTO city(id,province_id,name,en_name) VALUES ('39', '3', ' گرمی', 'Germi');
INSERT INTO city(id,province_id,name,en_name) VALUES ('40', '3', ' مشگین', 'Meshginshahr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('41', '3', ' نمین', 'Namin');
INSERT INTO city(id,province_id,name,en_name) VALUES ('42', '3', ' نیر', 'Nir');
INSERT INTO city(id,province_id,name,en_name) VALUES ('43', '4', ' آران و بیدگل', 'Aran va Bidgol');
INSERT INTO city(id,province_id,name,en_name) VALUES ('44', '4', ' اردستان', 'Ardestan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('45', '4', ' اصفهان', 'Isfahan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('46', '4', ' برخوار و میمه', 'Borkhar and M00000');
INSERT INTO city(id,province_id,name,en_name) VALUES ('47', '4', ' تیران و کرون','');
INSERT INTO city(id,province_id,name,en_name) VALUES ('48', '4', ' چادگان', 'Chadegan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('49', '4', ' خمینی شهر', 'Khomeyni Shahr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('50', '4', ' خوانسار', 'Khvansar');
INSERT INTO city(id,province_id,name,en_name) VALUES ('51', '4', ' سمیرم', 'Semirom');
INSERT INTO city(id,province_id,name,en_name) VALUES ('52', '4', ' شاهین شهر و میمه', 'Shahin Sha');
INSERT INTO city(id,province_id,name,en_name) VALUES ('53', '4', ' شهر رضا', 'Shahreza');
INSERT INTO city(id,province_id,name,en_name) VALUES ('54', '4', 'دهاقان', 'Dehaqan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('55', '4', ' فریدن', 'Faridan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('56', '4', ' فریدون شهر', 'Fereydunshahr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('57', '4', ' فلاورجان', 'Falavarjan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('58', '4', ' کاشان', 'Kashan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('59', '4', ' گلپایگان', 'Golpayegan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('60', '4', ' لنجان', 'Lenjan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('61', '4', ' مبارکه', 'Mobarakeh');
INSERT INTO city(id,province_id,name,en_name) VALUES ('62', '4', ' نائین', 'Nain');
INSERT INTO city(id,province_id,name,en_name) VALUES ('63', '4', ' نجف آباد', 'Najafabad');
INSERT INTO city(id,province_id,name,en_name) VALUES ('64', '4', ' نطنز', 'Natanz');
INSERT INTO city(id,province_id,name,en_name) VALUES ('65', '5', ' ساوجبلاق', 'Savojbolagh');
INSERT INTO city(id,province_id,name,en_name) VALUES ('66', '5', ' کرج', 'Karaj');
INSERT INTO city(id,province_id,name,en_name) VALUES ('67', '5', ' نظرآباد', 'Nazarabad');
INSERT INTO city(id,province_id,name,en_name) VALUES ('68', '5', 'طالقان', 'Taleqan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('69', '6', ' آبدانان', 'Abdanan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('70', '6', ' ایلام', 'Ilam');
INSERT INTO city(id,province_id,name,en_name) VALUES ('71', '6', ' ایوان', 'Eyvan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('72', '6', ' دره شهر', 'Darreh Shahr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('73', '6', ' دهلران', 'Dehloran');
INSERT INTO city(id,province_id,name,en_name) VALUES ('74', '6', ' شیران و چرداول', 'Chardavol');
INSERT INTO city(id,province_id,name,en_name) VALUES ('75', '6', ' مهران', 'Mehran');
INSERT INTO city(id,province_id,name,en_name) VALUES ('76', '7', ' بوشهر', 'Bushehr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('77', '7', ' تنگستان', 'Tangestan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('78', '7', ' جم', 'Jam');
INSERT INTO city(id,province_id,name,en_name) VALUES ('79', '7', ' دشتستان', 'Dashtestan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('80', '7', ' دشتی', 'Dashti');
INSERT INTO city(id,province_id,name,en_name) VALUES ('81', '7', ' دیر', 'Deyr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('82', '7', ' دیلم', 'Deylam');
INSERT INTO city(id,province_id,name,en_name) VALUES ('83', '7', ' کنگان', 'Kangan');
INSERT INTO city(id,province_id,name,en_name) VALUES ('84', '7', ' گناوه', 'Ganaveh');
INSERT INTO city(id,province_id,name,en_name) VALUES ('85', '8', ' اسلام شهر', 'Eslamshahr');
INSERT INTO city(id,province_id,name,en_name) VALUES ('86', '8', ' پاکدشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('87', '8', ' تهران', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('88', '8', ' دماوند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('89', '8', ' رباط کریم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('90', '8', ' ری', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('91', '8', ' شمیرانات', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('92', '8', ' شهریار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('93', '8', ' فیروزکوه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('94', '8', ' ورامین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('95', '9', ' اردل', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('96', '9', ' بروجن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('97', '9', ' شهرکرد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('98', '9', ' فارسان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('99', '9', ' کوهرنگ', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('100', '9', ' لردگان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('101', '10', ' بیرجند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('102', '10', ' درمیان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('103', '10', ' سرایان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('104', '10', ' سر بیشه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('105', '10', ' فردوس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('106', '10', ' قائن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('107', '10', ' نهبندان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('108', '11', ' برد سکن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('109', '11', ' بجستان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('110', '11', ' تایباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('111', '11',' تحت جلگه','');
INSERT INTO city(id,province_id,name,en_name) VALUES ('112', '11', ' تربت جام', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('113', '11', ' تربت حیدریه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('114', '11', ' چناران', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('115', '11', ' جغتای', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('116', '11', ' جوین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('117', '11', ' خلیل آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('118', '11', ' خواف', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('119', '11', ' درگز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('120', '11', ' رشتخوار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('121', '11', ' زاوه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('122', '11', ' سبزوار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('123', '11', ' سرخس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('124', '11', ' فریمان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('125', '11', ' قوچان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('126', '11', 'طرقبه شاندیز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('127', '11', ' کاشمر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('128', '11', ' کلات', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('129', '11', ' گناباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('130', '11', ' مشهد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('131', '11', ' مه ولات', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('132', '11', ' نیشابور', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('133', '12', ' اسفراین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('134', '12', ' بجنورد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('135', '12', ' جاجرم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('136', '12', ' شیروان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('137', '12', ' فاروج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('138', '12', ' مانه و سملقان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('139', '13', ' آبادان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('140', '13', ' امیدیه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('141', '13', ' اندیمشک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('142', '13', ' اهواز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('143', '13', ' ایذه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('144', '13', ' باغ ملک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('145', '13', ' بندرماهشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('146', '13', ' بهبهان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('147', '13', ' خرمشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('148', '13', ' دزفول', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('149', '13', ' دشت آزادگان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('150', '13', ' رامشیر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('151', '13', ' رامهرمز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('152', '13', ' شادگان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('153', '13', ' شوش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('154', '13', ' شوشتر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('155', '13', ' گتوند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('156', '13', ' لالی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('157', '13', ' مسجد سلیمان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('158', '13', ' هندیجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('159', '14', ' ابهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('160', '14', ' ایجرود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('161', '14', ' خدابنده', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('162', '14', ' خرمدره', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('163', '14', ' زنجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('164', '14', ' طارم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('165', '14', ' ماه نشان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('166', '15', ' دامغان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('167', '15', ' سمنان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('168', '15', ' شاهرود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('169', '15', ' گرمسار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('170', '15', ' مهدی شهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('171', '16', ' ایرانشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('172', '16', ' چابهار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('173', '16', ' خاش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('174', '16', ' دلگان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('175', '16', ' زابل', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('176', '16', ' زاهدان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('177', '16', ' زهک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('178', '16', ' سراوان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('179', '16', ' سرباز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('180', '16', ' کنارک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('181', '16', ' نیکشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('182', '17', ' آباده', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('183', '17', ' ارسنجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('184', '17', ' استهبان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('185', '17', ' اقلید', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('186', '17', ' بوانات', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('187', '17', ' پاسارگاد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('188', '17', ' جهرم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('189', '17', ' خرم بید', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('190', '17', ' خنج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('191', '17', ' داراب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('192', '17', ' زرین دشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('193', '17', ' سپیدان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('194', '17', ' شیراز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('195', '17', ' فراشبند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('196', '17', ' فسا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('197', '17', ' فیروزآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('198', '17', ' قیر و کارزین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('199', '17', ' کازرون', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('200', '17', ' لارستان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('201', '17', ' لامرد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('202', '17', ' مرودشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('203', '17', ' ممسنی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('204', '17', ' مهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('205', '17', ' نی ریز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('206', '18', ' آبیک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('207', '18', ' البرز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('208', '18', ' بوئین زهرا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('209', '18', ' تاکستان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('210', '18', ' قزوین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('211', '19', ' قم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('212', '20', ' بانه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('213', '20', ' بیجار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('214', '20', ' دیواندره', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('215', '20', ' سروآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('216', '20', ' سقز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('217', '20', ' سنندج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('218', '20', ' قروه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('219', '20', ' کامیاران', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('220', '20', ' مریوان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('221', '21', ' بافت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('222', '21', ' بردسیر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('223', '21', ' بم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('224', '21', ' جیرفت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('225', '21', ' راور', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('226', '21', ' رفسنجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('227', '21', ' رودبار جنوب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('228', '21', ' زرند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('229', '21', ' سیرجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('230', '21', ' شهر بابک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('231', '21', ' عنبرآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('232', '21', ' قلعه گنج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('233', '21', ' کرمان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('234', '21', ' کوهبنان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('235', '21', ' کهنوج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('236', '21', ' منوجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('237', '22', ' اسلام آباد غرب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('238', '22', ' پاوه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('239', '22', ' ثلاث باباجانی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('240', '22', ' جوانرود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('241', '22', ' دالاهو', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('242', '22', ' روانسر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('243', '22', ' سرپل ذهاب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('244', '22', ' سنقر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('245', '22', ' صحنه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('246', '22', ' قصر شیرین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('247', '22', ' کرمانشاه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('248', '22', ' کنگاور', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('249', '22', ' گیلان غرب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('250', '22', ' هرسین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('251', '23', ' بویر احمد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('252', '23','بهمئی','');
INSERT INTO city(id,province_id,name,en_name) VALUES ('253', '23', ' دنا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('254', '23','کهگیلویه','');
INSERT INTO city(id,province_id,name,en_name) VALUES ('255', '23', ' گچساران', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('256', '24', ' آزادشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('257', '24', ' آق قلا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('258', '24', ' بندر گز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('259', '24', ' بندر ترکمن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('260', '24', ' رامیان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('261', '24', ' علی آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('262', '24', ' کرد کوی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('263', '24', ' کلاله', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('264', '24', ' گرگان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('265', '24', ' گنبد کاووس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('266', '24', ' مینو دشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('267', '25', ' آستارا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('268', '25', ' آستانه اشرفیه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('269', '25', ' املش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('270', '25', ' بندر انزلی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('271', '25', ' رشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('272', '25', ' رضوانشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('273', '25', ' رودبار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('274', '25', ' رودسر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('275', '25', ' سیاهکل', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('276', '25', ' شفت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('277', '25', ' صومعه سرا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('278', '25', ' طوالش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('279', '25', ' فومن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('280', '25', ' لاهیجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('281', '25', ' لنگرود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('282', '25', ' ماسال', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('283', '26', ' ازنا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('284', '26', ' الیگودرز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('285', '26', ' بروجرد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('286', '26', ' پلدختر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('287', '26', ' خرم آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('288', '26', ' دورود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('289', '17', ' لامرد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('290', '17', ' مرودشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('291', '17', ' ممسنی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('292', '17', ' مهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('293', '17', ' نی ریز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('294', '18', ' آبیک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('295', '18', ' البرز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('296', '18', ' بوئین زهرا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('297', '18', ' تاکستان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('298', '18', ' قزوین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('299', '19', ' قم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('300', '20', ' بانه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('301', '20', ' بیجار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('302', '20', ' دیواندره', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('303', '20', ' سروآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('304', '20', ' سقز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('305', '20', ' سنندج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('306', '20', ' قروه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('307', '20', ' کامیاران', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('308', '20', ' مریوان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('309', '21', ' بافت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('310', '21', ' بردسیر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('311', '21', ' بم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('312', '21', ' جیرفت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('313', '21', ' راور', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('314', '21', ' رفسنجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('315', '21', ' رودبار جنوب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('316', '21', ' زرند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('317', '21', ' سیرجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('318', '21', ' شهر بابک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('319', '21', ' عنبرآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('320', '21', ' قلعه گنج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('321', '21', ' کرمان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('322', '21', ' کوهبنان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('323', '21', ' کهنوج', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('324', '21', ' منوجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('325', '22', ' اسلام آباد غرب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('326', '22', ' پاوه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('327', '22', ' ثلاث باباجانی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('328', '22', ' جوانرود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('329', '22', ' دالاهو', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('330', '22', ' روانسر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('332', '22', ' سنقر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('333', '22', ' صحنه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('334', '22', ' قصر شیرین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('335', '22', ' کرمانشاه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('336', '22', ' کنگاور', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('337', '22', ' گیلان غرب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('338', '22', ' هرسین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('339', '23', ' بویر احمد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('341', '23', ' دنا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('343', '23', ' گچساران', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('344', '24', ' آزادشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('345', '24', ' آق قلا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('346', '24', ' بندر گز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('347', '24', ' بندر ترکمن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('348', '24', ' رامیان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('349', '24', ' علی آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('350', '24', ' کرد کوی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('351', '24', ' کلاله', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('352', '24', ' گرگان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('353', '24', ' گنبد کاووس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('354', '24', ' مینو دشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('355', '25', ' آستارا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('356', '25', ' آستانه اشرفیه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('357', '25', ' املش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('358', '25', ' بندر انزلی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('359', '25', ' رشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('360', '25', ' رضوانشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('361', '25', ' رودبار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('362', '25', ' رودسر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('363', '25', ' سیاهکل', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('364', '25', ' شفت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('365', '25', ' صومعه سرا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('366', '25', ' طوالش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('367', '25', ' فومن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('368', '25', ' لاهیجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('369', '25', ' لنگرود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('370', '25', ' ماسال', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('371', '26', ' ازنا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('372', '26', ' الیگودرز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('373', '26', ' بروجرد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('374', '26', ' پلدختر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('375', '26', ' خرم آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('376', '26', ' دورود', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('377', '26', ' دلفان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('378', '26', ' سلسله', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('379', '26', ' کوهدشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('380', '26', ' الشتر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('381', '26', ' نورآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('382', '27', ' آمل', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('383', '27', ' بابل', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('384', '27', ' بابلسر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('385', '27', ' بهشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('386', '27', ' تنکابن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('387', '27', ' جویبار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('388', '27', ' چالوس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('389', '27', ' رامسر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('390', '27', ' ساری', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('391', '27', ' سوادکوه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('392', '27', ' قائم شهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('393', '27', ' گلوگاه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('394', '27', ' محمود آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('395', '27', ' نکا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('396', '27', ' نور', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('397', '27', ' نوشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('398', '27', ' فریدونکنار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('399', '28', ' آشتیان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('400', '28', ' اراک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('401', '28', ' تفرش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('402', '28', ' خمین', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('403', '28', ' دلیجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('404', '28', ' زرندیه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('405', '28', ' ساوه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('406', '28', ' شازند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('407', '28', ' کمیجان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('408', '28', ' محلات', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('409', '29', ' بندرعباس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('410', '29', ' میناب', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('411', '29', ' بندر لنگه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('412', '29', ' رودان-دهبارز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('413', '29', ' جاسک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('414', '29', ' قشم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('415', '29', ' حاجی آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('416', '29', ' ابوموسی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('417', '29', ' بستک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('418', '29', ' گاوبندی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('419', '29', ' خمیر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('420', '30', ' اسدآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('421', '30', ' بهار', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('422', '30', ' تویسرکان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('423', '30', ' رزن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('424', '30', ' کبودر آهنگ', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('425', '30', ' ملایر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('426', '30', ' نهاوند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('427', '30', ' همدان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('428', '31', ' ابرکوه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('429', '31', ' اردکان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('430', '31', ' بافق', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('431', '31', ' تفت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('432', '31', ' خاتم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('433', '31', ' صدوق', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('434', '31', ' طبس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('435', '31', ' مهریز', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('436', '31', ' میبد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('437', '31', ' یزد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('438', '8', 'قرچک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('439', '8', 'گلستان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('440', '8', 'قدس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('441', '8', 'ملارد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('442', '8', 'نسیم‌شهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('443', '8', 'اندیشه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('444', '8', 'صالح‌آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('445', '8', 'باقرشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('446', '8', 'باغستان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('447', '8', 'بومهن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('448', '8', 'چهاردانگه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('449', '8', 'پیشوا', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('450', '8', 'پردیس', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('451', '8', 'وحیدیه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('452', '8', 'نصیرآباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('453', '8', 'فردوسیه', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('454', '8', 'حسن‌آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('455', '8', 'رودهن', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('456', '8', 'شاهدشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('457', '8', 'صباشهر', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('458', '8', 'صفادشت', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('459', '8', 'لواسان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('460', '8', 'آبسرد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('461', '8', 'شریف‌آباد', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('462', '8', 'کهریزک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('463', '8', 'فشم', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('464', '8','جوادآباد','');
INSERT INTO city(id,province_id,name,en_name) VALUES ('465', '8', 'کیلان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('466', '8', 'آبعلی', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('467', '8', 'ارجمند', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('468', '29', 'کیش', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('469', '29', 'لاوان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('470', '29', 'پارسیان', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('471', '29', 'سیریک', '');
INSERT INTO city(id,province_id,name,en_name) VALUES ('472', '29', 'بشاگرد', '');
