INSERT INTO province VALUES ('1', 'آذربایجان شرقی', 'East Azerbaijan');
INSERT INTO province VALUES ('2', 'آذربایجان غربی', 'West Azerbaijan');
INSERT INTO province VALUES ('3', 'اردبیل', 'Ardabil');
INSERT INTO province VALUES ('4', 'اصفهان', 'Isfahan');
INSERT INTO province VALUES ('5', 'البرز', 'Alborz');
INSERT INTO province VALUES ('6', 'ایلام', 'Ilam');
INSERT INTO province VALUES ('7', 'بوشهر', 'Bushehr');
INSERT INTO province VALUES ('8', 'تهران', 'Tehran');
INSERT INTO province VALUES ('9', 'چهارمحال و بختیاری', 'Chaharmahal and Bakhtiari ');
INSERT INTO province VALUES ('10', 'خراسان جنوبی', 'South Khorasan');
INSERT INTO province VALUES ('11', 'خراسان رضوی', 'Razavi Khorasan');
INSERT INTO province VALUES ('12', 'خراسان شمالی', 'North Khorasan');
INSERT INTO province VALUES ('13', 'خوزستان', 'Khuzestan');
INSERT INTO province VALUES ('14', 'زنجان', 'Zanjan');
INSERT INTO province VALUES ('15', 'سمنان', 'Semnan');
INSERT INTO province VALUES ('16', 'سیستان و بلوچستان', 'Sistan and Baluchestan ');
INSERT INTO province VALUES ('17', 'فارس', 'Fars');
INSERT INTO province VALUES ('18', 'قزوین', 'Qazvin');
INSERT INTO province VALUES ('19', 'قم', 'Qom');
INSERT INTO province VALUES ('20', 'كردستان', 'Kurdistan');
INSERT INTO province VALUES ('21', 'كرمان', 'Kerman');
INSERT INTO province VALUES ('22', 'كرمانشاه', 'Kermanshah');
INSERT INTO province VALUES ('23', 'کهگیلویه و بویراحمد', 'Kohgiluyeh and Boyer-Ahmad ');
INSERT INTO province VALUES ('24', 'گلستان', 'Golestan');
INSERT INTO province VALUES ('25', 'گیلان', 'Gilan');
INSERT INTO province VALUES ('26', 'لرستان', 'Lorestan');
INSERT INTO province VALUES ('27', 'مازندران', 'Mazandaran');
INSERT INTO province VALUES ('28', 'مركزی', 'Markazi');
INSERT INTO province VALUES ('29', 'هرمزگان', 'Hormozgan');
INSERT INTO province VALUES ('30', 'همدان', 'Hamadan');
INSERT INTO province VALUES ('31', 'یزد', 'Yazd');
